image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: registry.gitlab.com/group13743924/cloud-devops-pipeline-aws/node-app

stages:
  - build_and_push
  - deploy

build_and_push:
  stage: build_and_push
  script:
    # Tag image with short SHA from commit
    - export IMAGE_TAG=$CI_COMMIT_SHORT_SHA
    - echo "Short SHA: $CI_COMMIT_SHORT_SHA"
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
    # Save tag for next job
    - echo "IMAGE_TAG=$IMAGE_TAG" > image_tag.env
  artifacts:
    reports:
      dotenv: image_tag.env

deploy:
  stage: deploy
  image: python:3.11-slim
  before_script:
    - pip install awscli
  script:
    - aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
    - aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
    - aws configure set region "$AWS_REGION"
    - echo "Deploying image: $IMAGE_NAME:$IMAGE_TAG"
    - aws ecs update-service --cluster node-app-cluster --service node-app-service --force-new-deployment













