# Use Docker as the base image for building and pushing container images
image: docker:latest

# Enable Docker-in-Docker service
services:
  - docker:dind

# Global variables used throughout the pipeline
variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: registry.gitlab.com/group13743924/cloud-devops-pipeline-aws/node-app

# Define pipeline stages
stages:
  - build_and_push
  - deploy

# Build and push the Docker image tagged with the current commit's short SHA
build_and_push:
  stage: build_and_push
  script:
   - echo "Building image with tag: $CI_COMMIT_SHORT_SHA"
   - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
   - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
   - echo "image_tag=$CI_COMMIT_SHORT_SHA" > image_tag.env

  artifacts:
    reports:
      dotenv: image_tag.env

# Use Terraform to update the ECS task definition with the new image tag
deploy:
  stage: deploy
  image: hashicorp/terraform:light
  before_script:
    - apk add --no-cache bash
    - echo "image_tag = \"$image_tag\"" > terraform.tfvars
  script:
    - terraform init
    - terraform apply -auto-approve

















