image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: registry.gitlab.com/group13743924/cloud-devops-pipeline-aws/node-app

stages:
  - build_and_push
  - deploy

build_and_push:
  stage: build_and_push
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest

deploy:
  stage: deploy
  image: amazon/aws-cli:2.15.12
  script:
    - echo "KEY: $AWS_ACCESS_KEY_ID"
    - echo "SECRET: $AWS_SECRET_ACCESS_KEY"
    - echo "REGION: $AWS_REGION"
    - aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
    - aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
    - aws configure set region "$AWS_REGION"
    - aws ecs update-service --cluster node-app-cluster --service node-app-service --force-new-deployment








