
image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - push
  - deploy

variables:
  IMAGE_NAME: registry.gitlab.com/group13743924/cloud-devops-pipeline-aws/node-app

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:latest .

push:
  stage: push
  script:
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker push $IMAGE_NAME:latest

deploy:
  stage: deploy
  script:
    - aws ecs update-service --cluster node-app-cluster --service node-app-service --force-new-deployment

