image: docker:20.10.16

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  AWS_REGION: us-east-1
  ECR_REPO: 203918869432.dkr.ecr.us-east-1.amazonaws.com/node-app-devops

stages:
  - build_and_push
  - deploy

build_and_push:
  stage: build_and_push
  before_script:
    - apk add --no-cache curl python3 py3-pip
    - pip3 install awscli
    - aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
    - aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
    - aws configure set region "$AWS_REGION"
    - export IMAGE_TAG=$CI_COMMIT_SHORT_SHA
    - echo "image_tag=$IMAGE_TAG" > image_tag.env  
    - aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_REPO
  script:
    - echo "Building image with tag:$IMAGE_TAG"
    - docker build -t $ECR_REPO:$IMAGE_TAG .
    - docker push $ECR_REPO:$IMAGE_TAG
  artifacts:
    paths:
      - image_tag.env   
    expire_in: 1 hour


deploy:
  stage: deploy
  image:
    name: hashicorp/terraform:light
    entrypoint: [""]
  before_script:
    - echo "Using image tag:$image_tag"
    - echo "image_tag = \"$image_tag\"" > terraform.tfvars
  script:
    - terraform init
    - terraform apply -auto-approve





























