
image: docker:latest

services:
  - docker:dind

stages:
  - build
  - push
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: $CI_REGISTRY_IMAGE/node-app

before_script:
  - docker info
  - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:latest .

push:
  stage: push
  script:
    - docker push $IMAGE_NAME:latest

deploy:
  stage: deploy
  script:
    - aws ecs update-service --cluster node-app-cluster --service node-app-service --force-new-deployment
