image: public.ecr.aws/aws-cli/aws-cli:2.15.12

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  AWS_REGION: us-east-1
  ECR_REPO: 203918869432.dkr.ecr.us-east-1.amazonaws.com/node-app-devops

stages:
  - build_and_push
  - deploy

build_and_push:
  stage: build_and_push
  before_script:
    - yum install -y docker  || apk add --no-cache docker  || apt-get update && apt-get install -y docker.io
    - aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
    - aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
    - aws configure set region "$AWS_REGION"
    - aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_REPO
  script:
    - export IMAGE_TAG=$CI_COMMIT_SHORT_SHA
    - echo "Building image with tag:$IMAGE_TAG"
    - docker build -t $ECR_REPO:$IMAGE_TAG .
    - docker push $ECR_REPO:$IMAGE_TAG
    - echo "image_tag=$IMAGE_TAG" > image_tag.env
  artifacts:
    reports:
      dotenv: image_tag.env

deploy:
  stage: deploy
  image:
    name: hashicorp/terraform:light
    entrypoint: [""]
  before_script:
    - echo "Using image tag:$image_tag"
    - echo "image_tag = \"$image_tag\"" > terraform.tfvars
  script:
    - terraform init
    - terraform apply -auto-approve

























