image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: registry.gitlab.com/group13743924/cloud-devops-pipeline-aws/node-app

stages:
  - build_and_push
  - deploy

build_and_push:
  stage: build_and_push
  script:
    - export IMAGE_TAG=$CI_COMMIT_SHORT_SHA
    - echo "Building image with tag: $IMAGE_TAG"
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - echo "image_tag=$IMAGE_TAG" > image_tag.env
  artifacts:
    reports:
      dotenv: image_tag.env

deploy:
  stage: deploy
  image: hashicorp/terraform:light
  before_script:
    - apk add --no-cache bash
    - echo "Using image tag: $image_tag"
    - echo "image_tag = \"$image_tag\"" > terraform.tfvars
  script:
    - terraform init
    - terraform apply -auto-approve




















